services:
  mysql:
    image: mysql:8.0
    container_name: quantity_measurement_mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Anvesh2005}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-quantitymeasurementapp}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    networks:
      - qm_network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pAnvesh2005"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s

    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: quantity_measurement_app

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/quantitymeasurementapp?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Anvesh2005}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      APP_JWT_SECRET: ${APP_JWT_SECRET:-13c41d0403bc2dfe9b7bb90fdaaf693a641bd9ebda82728369c4cbcded9605223b8a155529872a452562b084e66e3acfc9d135ab16f63923fba8f34509a0879b}
      APP_JWT_EXPIRATION_MS: 3600000

      APP_AUTH_NAME: App User
      APP_AUTH_EMAIL: appuser@example.com
      APP_AUTH_PASSWORD: app_password_123
      APP_AUTH_MOBILE_NUMBER: +15555550123
      APP_AUTH_ROLES: ROLE_USER

      # ✅ FIXED
      APP_OAUTH2_AUTHORIZED_REDIRECT_URI: http://localhost:4200/oauth2/callback

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-796770786907-nj0err3rv7vntsl1jb6gba2l04kh0fho.apps.googleusercontent.com}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-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}

    ports:
      - "8081:8081"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - qm_network

    restart: unless-stopped

volumes:
  mysql_data:

networks:
  qm_network:
    driver: bridge